# Generated by Django 4.2.1 on 2024-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=300, verbose_name='Informacion del producto'),
        ),
    ]
